export interface Localization {
  premium: 'premium',
  enter_premium_code: 'enter_premium_code',
  haptic_feedback: 'haptic_feedback',
  native_search_engine: 'native_search_engine',
  clear_search_history: 'clear_search_history',
  advanced_settings: 'advanced_settings',
  settings: 'settings',
  app_version: 'app_version',
  dictionary: 'dictionary',
  dictionarly: 'dictionarly',
  easy: 'easy',
  hard: 'hard',
  search_for_word: 'search_for_word',
  no_definitions_found: 'no_definitions_found',
  by_letters: 'by_letters',
  load_more: 'load_more',
  guideline_basic_search_headline: 'guideline_basic_search_headline'
  guideline_basic_search: 'guideline_basic_search',
  guideline_deselect_letters_headline: 'guideline_deselect_letters_headline',
  guideline_deselect_letters: 'guideline_deselect_letters',
  guideline_possible_words_details_headline: 'guideline_possible_words_details_headline',
  guideline_possible_words_details: 'guideline_possible_words_details',
  guideline_letters_position_headline: 'guideline_letters_position_headline',
  guideline_letters_position: 'guideline_letters_position',
  guideline_soap_letters_headline: 'guideline_soap_letters_headline',
  guideline_soap_letters: 'guideline_soap_letters',
  guideline_search_history_headline: 'guideline_search_history_headline',
  guideline_search_history: 'guideline_search_history',
  about_author: 'about_author',
  failed: 'failed',
  success: 'success',
  try_again: 'try_again',
  theme: 'theme',
  light: 'light',
  dark: 'dark',
  auto: 'auto',
  charade: 'charade',
  playground: 'playground',
  dashboard: 'dashboard',
  play: 'play',
  more: 'more',
  help: 'help',
  language: 'language',
}

export enum LANGUAGE_CODES {
  PL = 'pl',
  EN = 'en',
  DE = 'de',
}
